### ISSUE TITLE
[PE-D] Expected output for edit command in UG is inconsistent

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-4/tp#138]
![image.png](https://raw.githubusercontent.com/avellinwong01/ped/main/files/80ba8ea1-b287-465b-9627-9c1fc02a4f4e.png)

One example shows no output and the other shows the list before and after the edit

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: avellinwong01/ped#10

**Comment by zh1huang** [comment]
Duplicate of #164
