### ISSUE TITLE
[PE-D] Error message for delete function does not show the correct index number 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-4/tp#140]
![image.png](https://raw.githubusercontent.com/kyun99/ped/main/files/4cb80cb4-5beb-4c75-8212-f8f3cc2e93ca.png)

tried to delete a item with index not in `warehouse` but got an incorrect error message

Expected: Item with index 3 does not exist  

Actual: Item with index 2 does not exist

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: kyun99/ped#5

**Comment by zh1huang** [comment]
Duplicate of #134
