### ISSUE TITLE
[PE-D] Error reported for valid command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-4/tp#146]
![1635499693(1).png](https://raw.githubusercontent.com/Mist0919/ped/main/files/2407604b-0035-47fc-97d4-ea42fe063bd7.png)

The input 'add n/Calculus shlv/textbooks p/41 s/0 q/1 r/free' matches the format 'add n/NAME shlv/SHELF_NAME p/PURCHASE_PRICE s/SELLING_PRICE q/QUANTITY [r/REMARKS]' given in UG but got the response saying the add command format is incorrect.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Mist0919/ped#3

**Comment by t-l-xin** [comment]
Checked that the command works, could be because of the chinese unicode character, will include in the User Guide & warnings during program ru
<img width="474" alt="no issues" src="https://user-images.githubusercontent.com/79501457/140018812-bad57e5c-38f6-4410-b34a-9bd1242afb9e.PNG">
n.
