### ISSUE TITLE
[PE-D] Input format of report command as expected but error message shown instead

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-4/tp#162]
![image.png](https://raw.githubusercontent.com/kyun99/ped/main/files/7f23f1f5-5393-4762-aefb-b7e6c88ab3e7.png)

entered optional code but an error is shown

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: kyun99/ped#10

**Comment by t-l-xin** [comment]
The person type the command wrong.

YEAR-MONTH format as follows:

YYYY-MM

This information was already mentioned in the user guide.
<img width="765" alt="report format" src="https://user-images.githubusercontent.com/79501457/140021074-e32f0e1f-031a-4e03-8b89-17fad5541d67.PNG">
